import:
  target_col: &target_column 'rating'
  input: &import_input
    path: 'data/raw_data/'
    file_name: 'amazon.csv'

eda:
  target_col: *target_column
  input: *import_input
  target_map: &target_map {2.0: '1.0-2.0', 3.0: '2.1-3.0', 4.0: '3.1-4.0', 5.0: '4.1-5.0'}
  output:
    path: 'EDA/analysis/'
    report: 'report.txt'

preprocess:
  drop_columns: ['product_id']
  target_col: *target_column
  target_map: {2.0: '1.0-2.0', 3.0: '2.1-3.0', 4.0: '3.1-4.0', 5.0: '4.1-5.0'}
  input: *import_input
  output: &preprocess_output
    path: 'data/preprocessed/'
    file_name: 'data.parquet'

model:
  target_column: *target_column
  input: *preprocess_output
  feats_perc: 0.7
  output:
    path: 'data/model/'
    file_name: 'analysis.csv'
    report: 'analysis.txt'
